version: '3.8'
services:
  aws-demo:
    image: krisbanas/aws-demo:0.0.1-snapshot
    container_name: aws-demo
    ports:
      - 8080:8080
  s3-minio:
    image: minio/minio:latest
    container_name: s3-minio
    ports:
      - 9000:9000
    command: "server /data"
