version: '3.8'
services:
  s3-minio:
    image: minio/minio:latest
    container_name: s3-minio
    environment:
      - MINIO_DOMAIN=localhost
    ports:
      - 9000:9000
    command: "server /data"
