spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

s3:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  region: ${MINIO_REGION:us-east-1}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
